worlds:
  lobby:
    build: false
    break: false
    interact: false
    buckets: false
    pvp: false
    explosions: false
    fire: false
    pistons: false
    entity-change-block: false
    item-drop: false
    item-pickup: false
    hunger: false
    damage: false